// Root build.gradle file for MySecretary (v10.5 - Stable)
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // تحديث إصدار AGP ليتوافق تماماً مع Gradle 8.2 والبيئة السحابية
        classpath 'com.android.tools.build:gradle:8.1.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.10"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
